#encoding:utf-8


if  __name__ == '__main__':
    tmpcj=["OFFICE_BUILDDING", "FACTORY", "SCHOOL", "FUNERAL_HOME", "SECURITY", "GOVERNMENT","COMMUNICATION_BUSINESS", "GOVERNMENT_INSTITUTIONS", "LIBRARY", "TESTING_ STATION", "INDUSTRIAL_PARK", "COMPANY","MUSEUM", "CRH_STATION", "WHARF", "BUS_STATION", "PARK", "SERVICE_STATION","HIGH_SPEED_SERVICE_AREA", "TEMPLE", "TRAIN_STATION", "AIRPORT", "SUBWAY_STATION", "PUBLIC_TOILET","AIRPORT", "SUBWAY_STATION", "PUBLIC_TOILET", "HOSPITAL", "SCENICSPOT", "MARKET_PLACE","RESTAURANT", "ENTERTAINMENT_VENUE", "INTERNET_BAR", "SUPERMARKET", "BUILDING_MATERIALS_MARKET", "RETAIL_MARKET",                   "CAR_SHOP", "GYM", "THEATRE", "HOTEL", "GYMNASIUM", "CONFERENCE_EXHIBITION_CENTER","OTHER", "CONFERENCE_EXHIBITION_CENTER", "OTHER", "HOUSING_ESTATE", "COMMUNITY"]
    print len(tmpcj)
    tmpcjname=['SCENE_WORKING','SCENE_WORKING',' SCENE_WORKING',' SCENE_WORKING',' SCENE_WORKING',' SCENE_WORKING','SCENE_WORKING',' SCENE_WORKING',' SCENE_WORKING',' SCENE_WORKING',' SCENE_WORKING',' SCENE_WORKING','SCENE_WORKING',' SCENE_TRAVELING',' SCENE_TRAVELING',' SCENE_TRAVELING',' SCENE_TRAVELING',' SCENE_TRAVELING','SCENE_TRAVELING',' SCENE_TRAVELING',' SCENE_TRAVELING',' SCENE_TRAVELING',' SCENE_TRAVELING',' SCENE_TRAVELING','SCENE_TRAVELING',' SCENE_TRAVELING',' SCENE_TRAVELING',' SCENE_SERVICING',' SCENE_SERVICING',' SCENE_SERVICING','SCENE_SERVICING',' SCENE_SERVICING',' SCENE_SERVICING',' SCENE_SERVICING',' SCENE_SERVICING',' SCENE_SERVICING','SCENE_SERVICING',' SCENE_SERVICING',' SCENE_SERVICING',' SCENE_SERVICING',' SCENE_SERVICING',' SCENE_SERVICING','SCENE_SERVICING',' SCENE_SERVICING',' SCENE_SERVICING',' SCENE_LIVING',' SCENE_LIVING']
    print len(tmpcjname)
    tmpdict={}
    tmlist=[]
    for i in range(0,47):
        tmpdict={tmpcj[i]:tmpcjname[i]}
        tmlist.append(tmpdict)
    # tmlist.sort()
    print tmlist
